version: "3.9"
services:
  worker1:
    build: ./worker
    ports:
      - "3001:3000"
    environment:
      - PORT=3000

  worker2:
    build: ./worker
    ports:
      - "3002:3000"
    environment:
      - PORT=3000

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - worker1
      - worker2
